---
- include_role:
    name: python

- name: Ensure EPEL is enabled (required for many extras)
  yum:
    name: epel-release
    state: present
  when: ansible_distribution=="Amazon" or ansible_distribution=="RedHat"

- name: Install Flask (Ubuntu)
  apt:
    name: python3-flask
    state: present
  when: ansible_distribution=="Ubuntu"

- name: Install Flask (Amazon | RedHat)
  yum:
    name: python3-flask
    state: present
  when: ansible_distribution=="Amazon" or ansible_distribution=="RedHat"
...
