---
- name: Deploy Flask and Node.js Apps with PostgreSQL
  hosts: g1
  become: yes

  roles:
    - db
    - flask
    - node
    - artifacts

  tasks:
    - name: Update test page
      template:
        src: html.j2
        dest: /var/www/html/test.html
...