---
- name: Deploy Flask and Node.js Applications
  hosts: g1
  become: yes
  tasks:

    - name: Install dependencies
      apt:
        name:
          - git
          - python3
          - python3-pip
          - nodejs
          - npm
          - postgresql-server
          - postgresql-contrib
        state: present

    - name: Initialize PostgreSQL
      command: postgresql-setup initdb
      args:
        creates: /var/lib/pgsql/data/pg_hba.conf

    - name: Start and Enable PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Clone Flask and Node.js application repository
      git:
        repo: "https://github.com/valen5000/proj-6-dual_app_shared_db.git"
        dest: /home/fedora/proj-6-dual_app_shared_db
        version: main

    - name: Install Flask dependencies
      pip:
        requirements: /home/fedora/proj-6-dual_app_shared_db/flask-app/requirements.txt
        executable: pip3

    - name: Install Node.js dependencies
      npm:
        path: /home/fedora/proj-6-dual_app_shared_db/node-app
        state: present

    - name: Start Flask Application
      shell: "cd /home/fedora/proj-6-dual_app_shared_db/flask-app && nohup python3 app.py > flask.log 2>&1 &"
      async: 60
      poll: 0

    - name: Start Node.js Application
      shell: "cd /home/fedora/proj-6-dual_app_shared_db/node-app && nohup node app.js > node.log 2>&1 &"
      async: 60
      poll: 0
...