---
- name: Install PostgreSQL 14 from official repo on Fedora
  hosts: web3
  become: true

  tasks:

  - name: Download PostgreSQL 14 repo RPM for Fedora 41
    ansible.builtin.get_url:
      url: "https://download.postgresql.org/pub/repos/yum/14/fedora/fedora-41-x86_64/pgdg-fedora-repo-latest.noarch.rpm"
      dest: /tmp/pgdg-fedora-repo-latest.noarch.rpm

  - name: Install PostgreSQL 14 repo RPM
    ansible.builtin.yum:
      name: /tmp/pgdg-fedora-repo-latest.noarch.rpm
      state: present

  - name: Disable built-in PostgreSQL module (just in case)
    ansible.builtin.command: dnf -qy module disable postgresql

  - name: Install PostgreSQL 14 server and contrib
    ansible.builtin.yum:
      name:
        - postgresql14-server
        - postgresql14-contrib
      state: present

  - name: Initialize PostgreSQL 14 database
    ansible.builtin.command: /usr/pgsql-14/bin/postgresql-14-setup initdb
    args:
      creates: /var/lib/pgsql/14/data/PG_VERSION

  - name: Enable and start PostgreSQL 14 service
    ansible.builtin.systemd:
      name: postgresql-14
      enabled: true
      state: started
...