---
- name: Ensure Docker is running
  hosts: web3
  become: true
  vars:
    docker_host: "unix:///var/run/docker.sock"  
  tasks:
    - name: Ensure Docker service is running
      community.docker.docker_container:
        name: postgres15
        image: postgres:15
        state: started
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: mysecretpassword
        docker_host: "{{ docker_host }}"
...