---
- name: Deploy PostgreSQL with cross-platform support
  hosts: g1
  become: yes

  tasks:
    # Install PostgreSQL (same as before)
    - name: Install PostgreSQL (Ubuntu)
      apt:
        name: 
          - "postgresql"
          - "postgresql-contrib"
          - "libpq-dev"
          - "python3-psycopg2"
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install PostgreSQL (Fedora)
      ansible.builtin.dnf:
        name:
          - "postgresql-server"
          - "postgresql-contrib"
          - "python3-psycopg2"
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Install PostgreSQL (Amazon Linux)
      yum:
        name:
          - "postgresql15-server"
          - "postgresql15-contrib"
          - "python3-psycopg2"
        state: present
      when: ansible_distribution == 'Amazon'

    # Initialize DB
    - name: Check if PostgreSQL data directory exists (Non-Ubuntu)
      stat:
        path: /var/lib/pgsql/data
      register: pg_data_dir
      when: ansible_distribution != 'Ubuntu'

    - name: Initialize PostgreSQL DB (Non-Ubuntu)
      command: "/usr/bin/postgresql-setup --initdb"
      when: 
        - ansible_distribution != 'Ubuntu'
        - not pg_data_dir.stat.exists
      notify: restart postgresql

    # Configure service
    - name: Ensure PostgreSQL is running and enabled
      service:
        name: postgresql
        state: started
        enabled: yes

    # First configure authentication to allow password login
    - name: Get PostgreSQL version (Ubuntu)
      shell: |
        ls /etc/postgresql | head -n 1
      register: pg_version
      when: ansible_distribution == 'Ubuntu'
      changed_when: false

    - name: Allow password authentication (Ubuntu)
      lineinfile:
        path: "/etc/postgresql/{{ pg_version.stdout }}/main/pg_hba.conf"
        regexp: "^local\\s+all\\s+postgres\\s+"
        line: "local   all             postgres                                md5"
      when: ansible_distribution == 'Ubuntu'
      notify: restart postgresql

    - name: Allow password authentication (Non-Ubuntu)
      lineinfile:
        path: "/var/lib/pgsql/data/pg_hba.conf"
        regexp: "^local\\s+all\\s+postgres\\s+"
        line: "local   all             postgres                                md5"
      when: ansible_distribution != 'Ubuntu'
      notify: restart postgresql

    # Now set passwords
    - name: Set postgres admin password (Ubuntu)
      postgresql_user:
        name: "chinelo"
        password: "chinelo"
        role_attr_flags: "SUPERUSER"
        login_user: "postgres"
        login_password: ""
        login_host: "localhost"
      when: ansible_distribution == 'Ubuntu'

    - name: Set postgres admin password (Non-Ubuntu)
      postgresql_user:
        name: "chinelo"
        password: "chinelo"
        role_attr_flags: "SUPERUSER"
        login_user: "postgres"
        login_password: ""
        login_host: "localhost"
      when: ansible_distribution != 'Ubuntu'

    # Configure application authentication
    - name: Allow application connections
      lineinfile:
        path: "{{ '/etc/postgresql/' + pg_version.stdout + '/main/pg_hba.conf' if ansible_distribution == 'Ubuntu' else '/var/lib/pgsql/data/pg_hba.conf' }}"
        line: "host    all             chinelo             127.0.0.1/32            md5"
      notify: restart postgresql

    - name: Create application user
      postgresql_user:
        name: "chinelo"
        password: "chinelo"
        role_attr_flags: "CREATEDB,LOGIN"
        state: present

    - name: Create database
      postgresql_db:
        name: "chinelo"
        owner: "chinelo"
        state: present

  handlers:
    - name: restart postgresql
      service:
        name: postgresql
        state: restarted
...        