---
- name: Setup PostgreSQL on Fedora
  hosts: web3
  become: true
  tasks:

    - name: Update package metadata
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: Install PostgreSQL packages (from Fedora repos)
      ansible.builtin.yum:
        name:
          - postgresql-server
          - postgresql
        state: present

    - name: Initialize PostgreSQL DB
      ansible.builtin.command: postgresql-setup --initdb

    - name: Enable and start PostgreSQL service
      ansible.builtin.systemd:
        name: postgresql
        enabled: true
        state: started
...