---
- name: Deploy PostgreSQL with cross-platform support
  hosts: g1
  become: yes
  vars:
    db_user: "app_user"
    db_password: "your_secure_password"
    db_name: "shared_db"

  tasks:
    # Install PostgreSQL
    - name: Install PostgreSQL (Ubuntu)
      apt:
        name: 
          - "postgresql"
          - "postgresql-contrib"
          - "libpq-dev"
          - "python3-psycopg2"
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install PostgreSQL (Fedora)
      ansible.builtin.dnf:  # Changed from dnf to ansible.builtin.dnf
        name:
          - "postgresql-server"
          - "postgresql-contrib"
          - "python3-psycopg2"
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Install PostgreSQL (Amazon Linux)
      yum:
        name:
          - "postgresql15-server"
          - "postgresql15-contrib"
          - "python3-psycopg2"
        state: present
      when: ansible_distribution == 'Amazon'

    # Initialize DB - Skip if already initialized
    - name: Check if PostgreSQL data directory exists (Non-Ubuntu)
      stat:
        path: /var/lib/pgsql/data
      register: pg_data_dir
      when: ansible_distribution != 'Ubuntu'

    - name: Initialize PostgreSQL DB (Non-Ubuntu)
      command: "/usr/bin/postgresql-setup --initdb"
      when: 
        - ansible_distribution != 'Ubuntu'
        - not pg_data_dir.stat.exists
      notify: restart postgresql

    # Configure service
    - name: Ensure PostgreSQL is running and enabled
      service:
        name: postgresql
        state: started
        enabled: yes

    # Configure authentication - Simplified path detection
    - name: Find PostgreSQL version (Ubuntu)
      shell: |
        pg_lsclusters | awk 'NR==1 {print $1}'
      register: pg_version
      when: ansible_distribution == 'Ubuntu'
      changed_when: false

    - name: Configure password authentication (Ubuntu)
      lineinfile:
        path: "/etc/postgresql/{{ pg_version.stdout }}/main/pg_hba.conf"
        regexp: "^host\\s+all\\s+all\\s+127.0.0.1/32\\s+"
        line: "host    all             all             127.0.0.1/32            md5"
      when: ansible_distribution == 'Ubuntu'
      notify: restart postgresql

    - name: Configure password authentication (Non-Ubuntu)
      lineinfile:
        path: "/var/lib/pgsql/data/pg_hba.conf"
        regexp: "^host\\s+all\\s+all\\s+127.0.0.1/32\\s+"
        line: "host    all             all             127.0.0.1/32            md5"
      when: ansible_distribution != 'Ubuntu'
      notify: restart postgresql

    # Database setup - Fixed user/database names to use variables
    - name: Set postgres user password
      postgresql_user:
        name: "postgres"
        password: "{{ db_password }}"
        role_attr_flags: "SUPERUSER"
        login_unix_socket: "/var/run/postgresql"
        login_user: "postgres"

    - name: Create PostgreSQL user
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        role_attr_flags: "CREATEDB,LOGIN"
        state: present

    - name: Create database
      postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
        state: present

  handlers:
    - name: restart postgresql
      service:
        name: postgresql
        state: restarted
...        