---
- include_role:
    name: update_cache
  
- name: Update release
  yum:
    name: epel-release

- name: Install dependencies
  yum: name={{ item }} state=present
  become: true
  with_items:
    - wget
    - python-psycopg2

# - name: Install postgresql
#   import_role:
#     name: linux-system-roles.postgresql
#   become: yes
#   become_user: root

# - name: Initialize PostgreSQL
#   shell: "postgresql-setup initdb"

# - name: Start and enable the service
#   service: "name={{item}} state=started enabled=yes"
#   with_items:
#     - postgresql

# - name: "Create db user"
#   community.postgresql.postgresql_user:
#     state: present
#     name: "{{ db_user }}"
#     password: "{{ db_password }}"
#   become: true
#   become_user: postgres
...