---
- name: Install PostgreSQL packages
  apt:
    name: postgresql postgresql-contrib
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  tags: install

- name: Create database
  postgresql_db:
    name: "{{ db_name }}"
  become: true
  become_user: postgres
  tags: db

- name: Create database user
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: postgres
  tags: user

- name: Grant privileges
  postgresql_privs:
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    privs: ALL
  become: true
  become_user: postgres
  tags: privileges
...