---
- name: Install PostgreSQL
  package:
    name: "{{ 'postgresql postgresql-contrib' if ansible_distribution == 'Ubuntu' else 'postgresql-server' }}"
    state: present

- name: Initialize DB (CentOS/Amazon)
  command: postgresql-setup initdb
  when: ansible_distribution in ["CentOS", "Amazon"]

- name: Start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Create database with proper auth
  postgresql_db:
    name: "{{ db_name }}"
    login_user: postgres
    login_unix_socket: /var/run/postgresql
  become: true
  become_user: postgres
...