---
- include_role:
    name: update_cache
  
- name: Install packages
  ansible.builtin.yum:
    name: 
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - postgresql-libs
      - python3-psycopg2
    state: present

- name: Check if installed
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: Check if installed
  ansible.builtin.shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: Start and enable service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

# - name: Install postgresql
#   import_role:
#     name: linux-system-roles.postgresql
#   become: yes
#   become_user: root

# - name: Initialize PostgreSQL
#   shell: "postgresql-setup initdb"

# - name: Start and enable the service
#   service: "name={{item}} state=started enabled=yes"
#   with_items:
#     - postgresql

# - name: "Create db user"
#   community.postgresql.postgresql_user:
#     state: present
#     name: "{{ db_user }}"
#     password: "{{ db_password }}"
#   become: true
#   become_user: postgres
...