---
- name: Set ansible configuration to disable ACLs
  set_fact:
    ansible_become_flags: ""

- include_role:
    name: update_cache

- name: Install postgresql (Ubuntu)
  apt:
    name: postgresql
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install postgresql (Amazon|CentOs)
  yum:
    name: postgresql
    state: present
  when: ansible_distribution == "Amazon" or ansible_distribution == "CentOs"

- name: Create dedicated ansible temp directory
  file:
    path: /var/lib/ansible-tmp
    state: directory
    owner: root
    group: root
    mode: '1777'

- name: Create postgres-specific temp directory
  file:
    path: /var/lib/ansible-tmp/postgres
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: "Create app database"
  postgresql_db:
    state: present
    name: "{{ db_name }}"
  become: true
  become_user: postgres
  vars:
    ansible_become_flags: ""
  environment:
    ANSIBLE_REMOTE_TMP: /var/lib/ansible-tmp/postgres
    ANSIBLE_TMP_DIR: /var/lib/ansible-tmp/postgres

- name: "Create db user"
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: postgres
  vars:
    ansible_become_flags: ""
  environment:
    ANSIBLE_REMOTE_TMP: /var/lib/ansible-tmp/postgres
    ANSIBLE_TMP_DIR: /var/lib/ansible-tmp/postgres

- name: "Grant db user access to app db"
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    roles: "{{ db_user }}"
    grant_option: no
    privs: all
  become: true
  become_user: postgres
  vars:
    ansible_become_flags: ""
  environment:
    ANSIBLE_REMOTE_TMP: /var/lib/ansible-tmp/postgres
    ANSIBLE_TMP_DIR: /var/lib/ansible-tmp/postgres

- name: "Find pg_hba.conf location"
  become: true
  become_user: postgres
  command: psql -t -c "SHOW hba_file;"
  register: pg_hba_path
  changed_when: false
  
- name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
    dest: "{{ pg_hba_path.stdout.strip() }}"
    contype: host
    databases: all
    method: md5
    users: "{{ db_user }}"
    create: true
  become: true
  become_user: postgres
  vars:
    ansible_become_flags: ""
  notify: restart postgres
...