---
- include_role:
    name: update_cache

- name: Install postgresql (Ubuntu)
  apt:
    name: postgresql
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install postgresql (Amazon|RedHat)
  yum:
    name:
      - postgresql15
      - postgresql15-server
      - python3-psycopg2
    state: present
  when: ansible_distribution == "Amazon" or ansible_distribution == "RedHat"


- name: Check if postgresql is initialized
  stat:
    path: /var/lib/pgsql/data/pg_hba.conf
  register: postgres_data

- name: Initialize PostgresSQL
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists


- name: "Start and enable postgresql"
  service:
    name: postgresql 
    state: started 
    enabled: true

- name: "Create db user"
  community.postgresql.postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: postgres

- name: Create app database
  become_user: postgres
  shell: psql -f /opt/node-app/db/init.sql

- name: "Allow md5 connection for the db user"
  postgresql_pg_hba:
    dest: "~/data/pg_hba.conf"
    contype: host
    databases: all
    method: md5
    users: "{{ db_user }}"
    create: true
  become: true
  become_user: postgres  

- name: "Restart postgres"
  service:
    name: postgresql
    state: restarted  
...