---
- name: Application Deployment
  hosts: ubuntu, redhat, centos
  become: true
  vars_files:
    ansible_remote_tmp: /tmp/.ansible
  roles:
    - install_postgresql
    - flask
    - node
    - setup_service
...