---
- include_role:
    name: update_cache

- name: Install Node (Ubuntu)
  apt:
    name: 
      - nodejs
      - npm
    state: present
  when: ansible_distribution=="Ubuntu"

- name: Install Node (Amazon | Centos)
  yum:
    name: 
      - nodejs
      - npm
    state: present
  when: ansible_distribution=="Amazon" or ansible_distribution=="RedHat"
...
