---
- include_role:
    name: 
      - update_cache

- name: Install postgresql (Ubuntu)
  apt:
    name: postgresql
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install postgresql (Amazon|RedHat)
  yum:
    name: postgresql
    state: present
  when: ansible_distribution == "Amazon" or ansible_distribution == "RedHat"


- name: Create app database
  become: true
  become_user: postgres
  shell: psql -f /opt/node_app/db/init.sql

- name: "Create db user"
  community.postgresql.postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: "{{ db_password }}"
  become: true
  become_user: postgres
...